on:
  workflow_run:
    workflows: ["Bump Version"]
    types:
      - completed

name: Create Release

jobs:
  publish:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Create Release
        run: ./makeRelease.sh v$(./getVersion.sh ANDROID_VERSION_NAME) ReleaseMessage ${TOKEN}
        env:
          TOKEN: ${{ secrets.TOKEN }}
