on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: ./makeRelease v$(./getVersion.sh) ReleaseMessage ${TOKEN}
        env:
          TOKEN: ${{ secrets.NPM_TOKEN }}
