# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hi
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: "Run a curl request"
        run: |
          curl --location --request GET 'https://ybpoq9phol.execute-api.eu-west-2.amazonaws.com/prod?name=${{ secrets.NAME }}&company=duk'
          echo "done"
          
      - name: "Run a curl request"
        run: |
          chmod u+x ./bash.sh
          ls -la
          ./bash.sh
