name: Test Variable
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Versioning type of increment version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  create_release:
      name: "Build Bundles"
      runs-on: ubuntu-latest
      steps:
        - name: Check-out sourcecode
          uses: actions/checkout@v3

        - name: "Test"
          run: |
              echo "testVar: $testVar" 
              chmod +x test.sh
              test.sh
              echo "testVar: $testVar" 
