name: Test Variable
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Versioning type of increment version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  test:
    runs-on: ubuntu-latest
          
    steps:
      - name: "Create GitHub Release"
        id: create_guthub_release
        run: |
          ls -la
          chmod +x ./scripts/makeRelease.sh
          ./scripts/makeRelease.sh
        
      - name: "Upload Bundles to GitHub-Release"
        env:
          Asset_Id: ${{needs.create_guthub_release.outputs.ASSET_ID}}
        run: |
          echo ${Asset_Id}
