name: Test Variable
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Versioning type of increment version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
          fav-animal: tiger
          fav-number: ${{steps.abc.outputs.FAV_NUMBER}}
    steps:
      - name: Do Work
        run: |
          echo '::set-output name=FAV_NUMBER::3'
          echo '::set-output name=FAV_COLOR::blue'
        id: abc
      
      - name: Read output
        run: |
          echo "${{steps.abc.outputs.FAV_NUMBER}}"
          echo "${{steps.abc.outputs.FAV_COLOR}}"
