name: Test Variable
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Versioning type of increment version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ Steps.test_env.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v1
      - name: Test envs
        id: test_env
        run: |
              chmod +x ./test.sh
              ./test.sh
              echo ${{ steps.branch_name.outputs.BRANCH_NAME }}
