name: Test Variable
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Versioning type of increment version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
env:
  FOO_ROOT: bar on root

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FOO_JOB: bar on job
    steps:
      - uses: actions/checkout@v1
      - name: Test envs
        run: |
              echo "FOO_ROOT: $FOO_ROOT"
              echo "FOO_JOB: $FOO_JOB" 
              echo "FOO_STEP: $FOO_STEP" 
              chmod +x ./test.sh
              ./test.sh
              echo "FOO_ROOT: $FOO_ROOT"
              echo "FOO_JOB: $FOO_JOB" 
              echo "FOO_STEP: $FOO_STEP"
              echo "VERSION: $VERSION"
        env:
          FOO_STEP: bar on step
